{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "dockerizer-backend.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "dockerizer-backend.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          - path: /api/v1alpha1/login
            pathType: Prefix
            backend:
              service:
                name: {{ $.Values.ingress.aipubBackend.serviceName }}
                port:
                  number: {{ $.Values.ingress.aipubBackend.servicePort }}
          - path: /api/v1alpha1/logout
            pathType: Prefix
            backend:
              service:
                name: {{ $.Values.ingress.aipubBackend.serviceName }}
                port:
                  number: {{ $.Values.ingress.aipubBackend.servicePort }}
          - path: /api/v1alpha1/selfsubjectreviews
            pathType: Prefix
            backend:
              service:
                name: {{ $.Values.ingress.aipubBackend.serviceName }}
                port:
                  number: {{ $.Values.ingress.aipubBackend.servicePort }}
          - path: /api/v1alpha1/k8sproxy
            pathType: Prefix
            backend:
              service:
                name: {{ $.Values.ingress.aipubBackend.serviceName }}
                port:
                  number: {{ $.Values.ingress.aipubBackend.servicePort }}
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: {{ include "dockerizer-backend.fullname" $ }}
                port:
                  name: http
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ $.Values.ingress.frontend.serviceName }}
                port:
                  number: {{ $.Values.ingress.frontend.servicePort | default 80 }}
    {{- end }}
{{- end }}
