{{- if and .Values.ingress.enabled (ne .Values.ingress.aipubBackend.serviceNamespace .Release.Namespace) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.ingress.aipubBackend.serviceName }}-external
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "backend-server.labels" . | nindent 4 }}
spec:
  type: ExternalName
  externalName: {{ .Values.ingress.aipubBackend.serviceName }}.{{ .Values.ingress.aipubBackend.serviceNamespace }}.svc.cluster.local
{{- end }}
