{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "backend-server.fullname" . }}-postgresql
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "backend-server.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
spec:
  type: ClusterIP
  ports:
    - name: tcp-postgresql
      port: 5432
      targetPort: tcp-postgresql
  selector:
    {{- include "backend-server.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
{{- end }}
