{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "backend-server.fullname" . }}-postgresql
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "backend-server.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
type: Opaque
data:
  postgresql-password: {{ .Values.postgresql.auth.password | b64enc | quote }}
{{- end }}
